	   SELECT FEE_NO, f.APT_NO, TO_CHAR(FEE_DATE, 'YYYY-MM-DD') FEE_DATE, TO_CHAR(DUE_DATE, 'YYYY-MM-DD'), APT_FEE
	     FROM FEE f
	     JOIN MEMBER a USING(USER_NO)
	    WHERE f.APT_NO = (SELECT APT_NO
	    				  FROM MEMBER
	    				 WHERE USER_NO = 2)
        AND FEE_DATE BETWEEN TRUNC(ADD_MONTHS(sysdate,-3)+1) - TO_CHAR(sysdate,'DD')
        AND TRUNC(LAST_DAY(sysdate)) + 0.99999421;